language: python
python:
  - "3.8"
services:
  - docker

install:
  - cd $TRAVIS_BUILD_DIR
  - ./bin/install_ci_dependencies.sh

jobs:
  include:
    - stage: test
      script: 
        - cd ./frontend
        - docker build --target builder -t mct-frontend:$TRAVIS_COMMIT_test .
        - docker run --entrypoint yarn mct-frontend:$TRAVIS_COMMIT_test test
      install: skip
    - stage: deploy
      if: branch = YALEMCT-59-obtain-facilities
      script:
        - cd ./frontend
        - docker build -t mct-frontend:$TRAVIS_COMMIT .
        - cd $TRAVIS_BUILD_DIR
        - ./bin/deploy.sh
