language: python
python:
  - "3.8"
services:
  - docker

install:
  - cd $TRAVIS_BUILD_DIR
  - ./bin/install_ci_dependencies.sh

jobs:
  include:
    - stage: test
      script: 
        - cd ./frontend
        - docker build --target builder -t mct-frontendtest:$TRAVIS_COMMIT .
        - docker run --entrypoint yarn mct-frontendtest:$TRAVIS_COMMIT test-ci
      install: skip
    - stage: deploy
      if: branch = main
      script:
        - docker build -t mct-frontend:$TRAVIS_COMMIT ./frontend
        - DOCKER_BUILDKIT=1 docker build -t mct-backend:$TRAVIS_COMMIT ./java
        - cd $TRAVIS_BUILD_DIR
        - ./bin/deploy.sh
