apiVersion: v1
kind: Service
metadata:
  name: mct-ig
  namespace: mct
  labels:
    tag: latest
spec:
  type: LoadBalancer
  selector:
    app: mct-ig
  ports:
  - name: http 
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mct-ig
  labels:
    app: mct-ig
    tag: latest
  namespace: mct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mct-ig
  template:
    metadata:
      labels:
        app: mct-ig
    spec:
      containers:
      - image: {{ .Values.aws.account_id }}.dkr.ecr.us-east-1.amazonaws.com/mct-ig:latest
        name: mct-ig
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mct-ig-latest
  namespace: mct
spec:
  defaultBackend:
    service:
      name: mct-ig-latest
      port: 
        number: 80
