export const issueTypesMap = {
  invalid: "Invalid Content	Content invalid against the specification or a profile.", 
  structure	: "Structural Issue	A structural issue in the content such as wrong namespace, unable to parse the content completely, invalid syntax, etc.", 
  required	: "Required element missing	A required element is missing.", 
  value	: "Element value invalid	An element or header value is invalid.", 
  invariant	: "Validation rule failed	A content validation rule failed - e.g. a schematron rule.", 
  security	: "Security Problem	An authentication/authorization/permissions issue of some kind.", 
  login	: "Login Required	The client needs to initiate an authentication process.", 
  unknown	: "Unknown User	The user or system was not able to be authenticated (either there is no process, or the proferred token is unacceptable).", 
  expired	: "Session Expired	User session expired; a login may be required.", 
  forbidden	: "Forbidden	The user does not have the rights to perform this action.", 
  suppressed	: "Information Suppressed	Some information was not or might not have been returned due to business rules, consent or privacy rules, or access permission constraints. This information may be accessible through alternate processes.", 
  processing	: "Processing Failure", 
  "not-supported": "Content not supported	The interaction, operation, resource or profile is not supported.", 
  duplicate	: "Duplicate	An attempt was made to create a duplicate record.", 
  "multiple-matches": "Multiple Matches	Multiple matching records were found when the operation required only one match.", 
  "not-found": "Not Found	The reference provided was not found. In a pure RESTful environment, this would be an HTTP 404 error, but this code may be used where the content is not found further into the application architecture.", 
  deleted	: "Deleted	The reference pointed to content (usually a resource) that has been deleted.", 
  "too-long": "Content Too Long	Provided content is too long (typically, this is a denial of service protection type of error).", 
  "code-invalid": "Invalid Code	The code or system could not be understood, or it was not valid in the context of a particular ValueSet.code.", 
  extension	: "Unacceptable Extension	An extension was found that was not acceptable, could not be resolved, or a modifierExtension was not recognized.", 
  "too-costly": "Operation Too Costly	The operation was stopped to protect server resources; e.g. a request for a value set expansion on all of SNOMED CT.", 
  "business-rule": "Business Rule Violation	The content/operation failed to pass some business rule and so could not proceed.", 
  conflict	: "Edit Version Conflict	Content could not be accepted because of an edit conflict (i.e. version aware updates). (In a pure RESTful environment, this would be an HTTP 409 error, but this code may be used where the conflict is discovered further into the application architecture.).", 
  transient	: "Transient Issue	Transient processing issues. The system receiving the message may be able to resubmit the same content once an underlying issue is resolved.", 
  "lock-error": "Lock Error	A resource/record locking failure (usually in an underlying database).", 
  "no-store": "No Store Available	The persistent store is unavailable; e.g. the database is down for maintenance or similar action, and the interaction or operation cannot be processed.", 
  exception	: "Exception	An unexpected internal error has occurred.", 
  timeout	: "Timeout	An internal timeout has occurred.", 
  incomplete	: "Incomplete Results	Not all data sources typically accessed could be reached or responded in time, so the returned information might not be complete (applies to search interactions and some operations).", 
  throttled	: "Throttled	The system is not prepared to handle this request due to load management.", 
  informational	: "Informational Note", 
}


